pipeline:
  sampling_rate: 16000
  frame_length_ms: 25.0
  frame_stride_ms: 10.0
  window_type: "hamming"
  pre_emphasis: 0.97

features:
  mfcc:
    n_mfcc: 40
    n_mels: 40
  lfcc:
    n_lfcc: 40
    n_filters: 40
  cqcc:
    B: 96
    d: 16
    cf: 19
    
stats:
  - "mean"
  - "std"
  - "skew"
  - "kurtosis"
  - "min"
  - "max"
  - "p5"
  - "p25"
  - "p50"
  - "p75"
  - "p95"