# configs/features.yaml
smoke_test: false
sample_rate: 16000

features:
  mfcc:
    n_mfcc: 24
    n_fft: 512
    hop_length: 160
    window: "hann"
  
  lfcc:
    n_lfcc: 20
    n_fft: 512
    hop_length: 160
    window: "hann"
  
  spectral:
    n_fft: 512
    hop_length: 160
    window: "hann"